name: Generate Datas

on:
  schedule: # execute every 12 hours
  - cron: "* */12 * * *"
  workflow_dispatch:
    
    jobs:
      build:
        name: Jobs to update datas
        runs-on: ubuntu-latest
        steps:
          # Snake Animation
          - uses: Platane/snk@master
          id: snake-gif
          with:
            github_user_name: muhammadbobur0
            svg_out_path: dist/github-contribution-grid-snake.svg
            
            - uses: crazy-max/ghaction-github-pages@v2.1.3
            with:
              target_branch: output
              build_dir: dist
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                
                name: "Connect4"
                
                on:
                  issues:
                    types: [opened]
                    
                    jobs:
                      move:
                        runs-on: ubuntu-latest
                        if: startsWith(github.event.issue.title, 'connect4|')
                        steps:
                          
                          - name: Checkout
                          uses: actions/checkout@v2.3.1
                          
                          - name: Setup Ruby
                          uses: ruby/setup-ruby@v1
                          with:
                            ruby-version: 2.7.1
                            
                            - name: Setup Gems
                            run: |
                            gem install octokit -N --silent
                            
                            - name: Play
                            env:
                              REPOSITORY: ${{ github.repository }}
                              EVENT_ISSUE_NUMBER: ${{ github.event.issue.number }}
                              EVENT_ISSUE_TITLE: ${{ github.event.issue.title }}
                              EVENT_USER_LOGIN: ${{ github.event.issue.user.login }}
                              run: |
                              ruby <<- EORUBY
                              require './connect4/runner'
                              
                              Connect4::Runner.new(
                              github_token: '${{ secrets.GITHUB_TOKEN }}',
                              issue_number: ENV.fetch('EVENT_ISSUE_NUMBER'),
                              issue_title: ENV.fetch('EVENT_ISSUE_TITLE'),
                              repository: ENV.fetch('REPOSITORY'),
                              user: ENV.fetch('EVENT_USER_LOGIN'),
                              ).run
                              EORUBY
                              
                              